### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by onnonym** [fornellas/tcg_opal_rootfs#1]
Hi,
thank you for getting back to on https://github.com/Drive-Trust-Alliance/sedutil/issues/90.

I have some questions, regarding your approach
1. Couldn't you just partition the disk and install the OS in one go before setting up the locking? The OS would still be encrypted after locking.
2. Couldn't you make the changes to the initrd before locking?
3. Can I have a /-partition and a separate /home-partition by just adding up the sectors to arrive at a $RANGE_LENGTH?

Best regards,

Onno

**Comment by fornellas** [comment]
> Couldn't you just partition the disk and install the OS in one go before setting up the locking? The OS would still be encrypted after locking.

In theory I think this is possible, though TBH, the whole spec is so complex / confusing, that I went for what worked for me :-P

> Couldn't you make the changes to the initrd before locking?

Initrd could be patched from the live install media, though that'd require setting up chroot and rbind mounting various filesystems, which IMHO would be more complex / error prone than doing a simple reboot. At the unlikely case that there's a poweroff in between, using the live media with chroot is still an option.

> Can I have a /-partition and a separate /home-partition by just adding up the sectors to arrive at a $RANGE_LENGTH?

Yes yes, you can basically mix and match this idea as you see fit. I suppose the "pro" of the spec is that it is hyper flexible. The "con" is that it is hyper flexible :-P
