### ISSUE TITLE
handling hibernation

### ISSUE THREAD

**Issue by Demetrio92** [fornellas/tcg_opal_rootfs#7]
I am thinking of extending this set up to allow for encrypted hibernation: 

* set up an unencrypted swap partition big enough for hibernation
* set a locking range 2 encapsulating it
* add it to the unlock here: https://github.com/fornellas/tcg_opal_rootfs/blob/master/initramfs-tools/scripts/init-premount/tcg_opal#L52

My understanding is that with hibernation `initramfs` is being triggered on resume, and as it's now patched to do unlocking as the very first step, we can first decrypt the root and swap partition and then resume.

**Comment by fornellas** [comment]
Humm... if the existing locking range fully covers the swap space, then I suppose "hybernation would just work", wouldn't it? IIRC unlocking happens before hibernation on initramfs, can't think of a reason why it'd not work. Have you tried it?

I haven't setup hibernation on my machine, and from what I've read, due to "low quality drivers", hibernation is still the same Schrodinger's cat it's been for 20 years...

PS: you should most definitely be locking your swap region anyway, as leaving swap region unlocked would potentially expose sensitive information, potentially including, the locking key itself...

**Comment by fornellas** [comment]
Indeed hibernation already works. I just did [this](https://ubuntuhandbook.org/index.php/2021/08/enable-hibernate-ubuntu-21-10/) and hibernation worked just fine. The only requirement is that the used swap partition is within the lock range. initramfs will correctly unlock the range, before resume is attempted, so resume "just works".

**Comment by Demetrio92** [comment]
So, swap file and win. This is great!

**Comment by Demetrio92** [comment]
> PS: you should most definitely be locking your swap region anyway, as leaving swap region unlocked would potentially expose sensitive information, potentially including, the locking key itself...

Which is a problem, cuz my swap partition is not locked. through sedutil, it uses cryptswap. Which is unsuitable for hibernation. Now I need to change the locking range, and something tells me I'll brick the system again. 

Or I just delete that partition and leave it as a buffer space and simply use a swap file.

**Comment by fornellas** [comment]
> Which is a problem, cuz my swap partition is not locked. through sedutil, it uses cryptswap. Which is unsuitable for hibernation. Now I need to change the locking range, and something tells me I'll brick the system again.

I'd do a backup and try it. Worst case, reset the drive and install again.

**Comment by Demetrio92** [comment]
> I'd do a backup and try it. Worst case, reset the drive and install again.

I got 2 nvme's, and still back-up takes 3-4h, restoring about 2.5h. When I feel like wasting another evening looking at `dd` progress bar, I might give it a try :D

**Comment by fornellas** [comment]
https://github.com/fornellas/tcg_opal_rootfs/commit/54be7e38d8b91ad72357940c30c523a3ce228401

Updated some details regarding hibernation support.
